CREATE TABLE _USER(
   USER_MAIL VARCHAR(50),
   USER_LASTNAME VARCHAR(50) NOT NULL,
   USER_FIRSTNAME VARCHAR(50) NOT NULL,
   PRIMARY KEY(USER_MAIL)
);

CREATE TABLE TASK(
   TASK_ID int AUTO_INCREMENT,
   TASK_NAME VARCHAR(50) NOT NULL,
   TASK_DESCRIPTION VARCHAR(200),
   TASK_FAVORITE BOOLEAN NOT NULL,
   TASK_DATE DATETIME,
   TASK_REMIND_DATE DATETIME,
   TASK_DEADLINE_DATE DATETIME,
   TASK_RECURRENCE_DATE DATETIME,
   USER_MAIL VARCHAR(50) NOT NULL,
   PRIMARY KEY(TASK_ID),
   FOREIGN KEY(USER_MAIL) REFERENCES _USER(USER_MAIL)
);

CREATE TABLE ATTACHEMENT(
   ATTACHEMENT_ID int AUTO_INCREMENT,
   ATTACHEMENT_URL VARCHAR(50),
   TASK_ID INT NOT NULL,
   PRIMARY KEY(ATTACHEMENT_ID),
   FOREIGN KEY(TASK_ID) REFERENCES TASK(TASK_ID)
);

CREATE TABLE STEP(
   STEP_ID int AUTO_INCREMENT,
   STEP_NAME VARCHAR(50),
   TASK_ID INT NOT NULL,
   PRIMARY KEY(STEP_ID),
   FOREIGN KEY(TASK_ID) REFERENCES TASK(TASK_ID)
);
